dukaan/urls.py
from django.contrib import admin
from django.urls import path, include
from meridukaan import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meridukaan.urls'))
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

urlpatterns += staticfiles_urlpatterns()
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meridukaan/urls.py
from django.urls import path
from .views import productlist, cart
from . import views

app_name = 'meridukaan'
urlpatterns = [
    path('', productlist.as_view(), name='home'),
    path('cart', views.cart, name='cart'),
    path('checkout', views.checkout, name='checkout'),
    path('update_item', views.updateItem, name='update_item'),
    path('process_order', views.processOrder, name='process_order')
]

meridukaan/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(max_length=200, null=True)
    
    def __str__(self):
        return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class Product(models.Model):
    # product_id = models.IntegerField(unique=True)
    category = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(default='no-image.jpeg', upload_to='images/')
    description = models.CharField(max_length=300)
    digital = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.name

class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=200, null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    pincode = models.IntegerField(null=False)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

meridukaan/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import JsonResponse
import json
import datetime
from .models import *
from .utils import cookieCart, cartData, guestOrder
# Create your views here.

class productlist(ListView): 
    model = Product
    queryset = Product.objects.all()[::-1]
    context_object_name = 'product_list'
    template_name = 'meridukaan/home.html'

def cart(request):
    data = cartData(request)
    order = data['order']
    items = data['items']

    for_front = {
        'items':items,
        'order':order,
    }
    return render(request, 'meridukaan/cart.html', for_front)

def checkout(request):
    data = cartData(request)
    order = data['order']
    items = data['items']

    for_front = {
        'items':items,
        'order':order,
    }
    return render(request, 'meridukaan/checkout.html', for_front)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('action:', action)
    print('productId:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action =='add':
        orderItem.quantity += 1
    elif action == 'remove':
        orderItem.quantity -= 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item Added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()    

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer = customer,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            pincode = data['shipping']['pincode'],
        )

    return JsonResponse('Order Processed', safe=False) 

meridukaan/templates/meridukaan/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'meridukaan/style.css' %}">    

    <script>
      var user = '{{ request.user }}'

      function getToken(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      const csrftoken = getToken('csrftoken');

      function getCookie(name){
        var cookieArr = document.cookie.split(";");

        for(var i=0; i<cookieArr.length; i++){
          var cookiePair = cookieArr[i].split("=");

          if(name == cookiePair[0].trim()){
            return decodeURIComponent(cookiePair[1]);
          }
        }
        return null;
      }

      var cart = JSON.parse(getCookie('cart'))
      if(cart == undefined){
        cart = {}      
        console.log("Cart was created.")
        document.cookie = "cart=" + JSON.stringify(cart) + "; domain=; path=/; samesite=lax; "
      }
      console.log('Cart:',cart)
    </script> 

    <title>Dukaan</title>
</head>
<body>
    <nav>
        <div class="nav-wrapper" id='nav-header'>
          <a href="{% url 'meridukaan:home' %}" class="brand-logo">MeriDukaan</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <a href="{% url 'meridukaan:cart' %}" id="cart-icon"><i class="material-icons hoverable">shopping_cart</i>{{ order.get_cart_items }}</a>
          <ul class="right hide-on-med-and-down">
            <li><a href="/">Home</a></li>
            <li><a href="/">LogIn</a></li>
            <li><a href="/">About Us</a></li>
            <!-- <li><a href="/"><i class="material-icons">shopping_cart</i></a></li> -->
          </ul>
        </div>  
    </nav>
    
    <ul class="sidenav left" id="mobile-demo">
        <li><a href="/"><h3>Categories</h3></a></li>
        <hr>
        {% for pc in product_list %}
        <li><a href="/">{{ pc.category }}</a></li>
        <li><div class="divider"></div></li><br>
        {% endfor %}
        <li><a href="/">Home</a></li>
        <li><a href="/">LogIn</a></li>
        <li><a href="/">About Us</a></li>
    </ul>
    
    {% block content %}
    {% endblock %}    

    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Footer Content</h5>
            <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Links</h5>
            <ul>
              <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
              <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
        </div>
      </div>
    </footer>


    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script> 
    <script data-require="jquery@3.1.1" data-semver="3.1.1" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'meridukaan/cart.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          var elems = document.querySelectorAll('.sidenav');
          var instances = M.Sidenav.init(elems, {draggable:'True'});
      });     
    </script>    
    
</body>
</html>

meridukaan/templates/meridukaan/cart.html
{% extends "meridukaan/base.html" %}
{% include "meridukaan/base.html" %}
{% block content %}

<div id='cart-card' class="container col s12 m12 l12">  
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">      
          <div class="row">
            <div class="col l4 m4 s12">
              Items: {{ order.get_cart_items }}
            </div>
            <div class="col l4 m4 s12">
              Total: Rs. {{ order.get_cart_total|floatformat:2}}
            </div>
            <div class="col l4 m4 s12">
              <a href="{% url 'meridukaan:checkout' %}" class="waves-effect waves-light btn right">Checkout</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

<div id='cart-card' class="container col s12 m12 l12">
  <div class="card horizontal">
    <div class="card-stacked">
      <div class="card-content">
        <!-- <div class="row">
          <div class="col l4 m4 s12">
            Img
          </div>
          <div class="col l3 m3 s12">
            Name
          </div>
          <div class="col l1 m1 s12">
            Price
          </div>
          <div class="col l2 m2 s12">
            Quantity
          </div>
          <div class="col l2 m2 s12">
            Total
          </div>
        </div>   -->

        <table class="responsive-table highlight">
          <thead>
            <tr>
                <th>Item Image</th>
                <th>Item Name</th>
                <th>Item Price</th>
                <th>Item Quantity</th>
                <th>Total Price</th>
            </tr>
          </thead>
          <tbody>
            {% for item in items %}
            <tr>
              <td><img src="{{ item.product.image.url }}" alt="" height="100px" width="200px"></td>
              <td>{{ item.product.name }}<p>{{ item.product.description }}</p></td>
              <td>Rs. {{ item.product.price|floatformat:2 }}</td>
              <td>
                <button class="btn btn-small btn-flat update-cart" data-product="{{ item.product.id }}" data-action="remove"><i class="material-icons">remove</i></button>
                {{ item.quantity }}
                <button class="btn btn-small btn-flat update-cart" data-product="{{ item.product.id }}" data-action="add"><i class="material-icons">add</i></button>               
              </td>
              <td>Rs. {{ item.get_total }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>             
      </div>
    </div>
  </div>
</div>

{% endblock %}

meridukaan/templates/meridukaan/checkout.html
{% extends "meridukaan/base.html" %}

{% block content %}

<div id='cart-card' class="container col s12 m12 l12">
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div>
          
          <a class="btn " style="display: inline-block; margin-top: 10px;" href="{% url 'meridukaan:cart' %}">Back To Cart</a><br><br>
          </div>
          <div class="row">
            <div class="col l8 m12 s12">
                <div class="row">                 
                  <form class="col s12" id="form">
                    {% csrf_token %}
                    <div id="user-info">
                    <div class="row">
                      <div class="input-field col s6">
                        <input id="name" type="text" class="validate" name='name' required>
                      <label for="name">Name</label>
                      </div>                  
                      <div class="input-field col s6">
                        <input id="email" type="email" class="validate" name="email" required>
                        <label for="email">Email</label>
                      </div>
                    </div>
                    </div>   
                    <div id="shipping-info">
                      <h5 class="left-align" style="display: inline-block;">Enter Address</h5> 
                    <div class="row">                     
                      <div class="input-field col s6">
                        <input id="address" type="text" class="validate" name="address" required>
                        <label for="address">Address</label>
                      </div>                  
                      <div class="input-field col s6">
                        <input id="city" type="text" class="validate" name="city" required>
                        <label for="city">City</label>
                      </div>
                    </div>  
                    <div class="row">
                      <div class="input-field col s6">
                        <input id="state" type="text" class="validate" name="state" required>
                        <label for="state">State</label>
                      </div>                  
                      <div class="input-field col s6">
                        <input id="pincode" type="number" class="validate" name="pincode" required>
                        <label for="pincode">PinCode</label>
                      </div>
                      </div>
                    </div>  
                    <ul class="collapsible left-align" id="payment-modal">
                      <li>
                        <div class="collapsible-header"><i class="large material-icons">payment</i><button class="btn white black-text" id="make-payment">Proceed for Payment</button> </div>
                        <div class="collapsible-body"><span>
                          <ul>
                            <li><div id="paypal-button-container"></div></li>
                          </ul>
                        </span></div>
                      </li>
                    </ul>

                    <!-- <button data-target="modal1" class="left-align btn modal-trigger" href="#" id="make-payment">Proceed for Payment</button>   -->
                    
                    <!-- Modal Structure -->
                    <div id="modal1" class="modal">
                      <div class="modal-content">
                        <h4>Modal Header</h4>
                        <p>A bunch of text</p>
                      </div>
                      <div class="modal-footer">
                        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
                      </div>
                    </div>

                                    
                  </form>                                
                </div>
            </div>
           
            <div class="col l4 m12 s12" id="order-summary">
              
              <h5>Order Summary</h5><hr><br>
              {% for item in items %}
                "{{ item.product.name }}" : {{ item.quantity }} : Rs. {{ item.get_total }}<br><br>
              {% endfor %}
              <hr>
              <p>Total Items: {{ order.get_cart_items }}</p><br>
              <p>Total Price: Rs. {{ order.get_cart_total }}</p>
              <hr>             
            </div>  
          </div> 
        </div>
      </div>
    </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=AZQzxDJjhqlEbV10e-AgO3V4luQc7qg7ti0EovYFrNdBwUjrG6JLRhGET4jCj6slT_gAAPZETQ0-e3_H&currency=USD">
</script>

<script>
  var total = '{{ order.get_cart_total}}'
  // Render the PayPal button into #paypal-button-container
  paypal.Buttons({

    style:{
      color:'blue',
      size:'responsive',
    },

  // Set up the transaction
  createOrder: function(data, actions) {
      return actions.order.create({
          purchase_units: [{
              amount: {
                  value: parseFloat(total).toFixed(2)
              }
          }]
      });
  },

  // Finalize the transaction
  onApprove: function(data, actions) {
      return actions.order.capture().then(function(details) {
        submitformdata()
      });
}


}).render('#paypal-button-container');

</script>

<script type="text/javascript">
  var shipping = '{{order.shipping}}'

  if(shipping == 'False'){
    document.getElementById('shipping-info').innerHTML = ''
  }

  if(user != 'AnonymousUser' && shipping == 'False'){
    document.getElementById('user-info').innerHTML = ''
    document.getElementById('shipping-info').innerHTML = ''
  }
  if(user != 'AnonymousUser'){
    document.getElementById('user-info').innerHTML = ''
  }

  var form = document.getElementById('form')

  csrf_token = form.getElementsByTagName('input')[0].value
  console.log('NewToken:', csrftoken)

  // document.getElementById('make-payment').addEventListener('click',
  //   function(e){
  //     submitformdata()
  //   })

  function submitformdata(){
      var userformdata = {
        'name':null,
        'email':null,
        'total':total
      }
      var shippingInfo = {
          'address':address,
          'city':city,
          'state':state,
          'pincode':pincode,    
      }

      if(shippingInfo != 'False'){
        shippingInfo.address = form.address.value
        shippingInfo.city = form.city.value
        shippingInfo.state = form.state.value
        shippingInfo.pincode = form.pincode.value
      }
      if(user=='AnonymousUser'){
        userformdata.name = form.name.value
        userformdata.email = form.email.value
      }

      var url = 'process_order'
      fetch(url, {
        method:"POST",
        headers:{
          'Content-Type': 'application/json',
          'X-CSRFToken': csrf_token,
        },
        body:JSON.stringify({'form':userformdata, 'shipping':shippingInfo})
      })
      .then((response) => response.json())
      .then((data) => {
        console.log('Success:', data);
        alert('Transaction Complete');

        cart = {}
        document.cookie = "cart=" + JSON.stringify(cart) + "; domain=; path=/"

        window.location.href = "{% url 'meridukaan:home' %}";
      })   
  }

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.collapsible');
    var instances = M.Collapsible.init(elems, {accordion:'True'});
  });

  $(document).ready(function(){
    $('.modal').modal();
  });

</script>

{% endblock %}

meridukaan/templates/meridukaan/home.html
{% extends "meridukaan/base.html" %}
{% load static %}

<!-- {{ product_list }} -->

{% include 'meridukaan/base.html' %}

{% block content %}

<div id='search' class="row">
    <div class="col m12 s12 l12">
      <nav class="container z-depth-2" id="search">
        <div class="nav-wrapper">
          <form>
            <div class="input-field">
              <input id="search" type="search" required >
              <label class="label-icon" for="search"><i class="material-icons">search</i></label>
              <i class="material-icons">close</i>
            </div>
          </form>
        </div>
      </nav>
    </div>
  </div>  

  <div id='card' class="row container">

    {% for p in product_list %}  

    <div class="col l4 m6 s12">
      <div class="card z-depth-3" id='cardid'>
        <div class="card-image">
          <img src="{{ p.image.url }}" id="pimage">
          <a class="btn-floating halfway-fab waves-effect waves-light blue-grey z-depth-5 update-cart" data-product="{{ p.id }}" data-action="add"><i class="material-icons">add_shopping_cart</i></a>
        </div>
        <div class="card-content"> 
          <div class="row">          
            <div class="col l6 s6 m6">              
              <h5>{{p.name}}</h5>
            </div>
            <div class="col l6 s6 m6">   
              <div class="right-align" style="float: right;"><h5>Rs. {{ p.price|floatformat:2 }}</h5></div>
            </div>
          </div>
          <div class="row">
            <div class="col l12 s12 m12">
              {{p.description}}
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endfor %}
    
  </div>
{% endblock %}